module.exports = {
    GRID_STYLE_PREFIX: '__q_grid__',
    COLUMN_STYLE_PREFIX: '__q_grid__column__',
    RESIZE: 'RESIZE',
    H_SCROLL: 'H_SCROLL',
    H_SCROLL_START: 'H_SCROLL_START',
    H_SCROLL_STOP: 'H_SCROLL_STOP',
    V_SCROLL: 'V_SCROLL',
    PIN_COLUMN: 'PIN_COLUMN',
    UPDATE_ROW_HEIGHT: 'UPDATE_ROW_HEIGHT',
    REMOVE_ROW: 'REMOVE_ROW'
};